name: Generate urls.txt

on:
  push:
    paths:
      - 'posts/**.html'
      - '.github/workflows/generate-urls.yml'
  workflow_dispatch:

jobs:
  generate-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate urls.txt from HTML files
        run: |
          BASE_URL="https://banglaguidenewsonline.online"
          find posts -name "*.html" > temp_paths.txt
          echo "" > urls.txt
          while read line; do
            echo "$BASE_URL/$line" >> urls.txt
          done < temp_paths.txt
          rm temp_paths.txt
          echo "Generated URLs:"
          cat urls.txt

      - name: Commit and push urls.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add urls.txt
          git commit -m "Auto-update urls.txt from HTML posts"
          git push
