name: Submit Sitemap to Google

on:
  push:
    branches:
      - main  # অথবা 'master' যদি তোমার main ব্রাঞ্চের নাম master হয়

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google with sitemap
        run: |
          curl "https://www.google.com/ping?sitemap=https://banglaguidenewsonline.online/sitemap.xml"
